# .github/workflows/java-ci.yml
# Build an Ant-based Java project on every push / PR to main.

name: Java CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1 ▸ Check out the repository
      - uses: actions/checkout@v4

      # 2 ▸ Install / configure Temurin OpenJDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      # (optional) 3 ▸ Echo the JDK version so you can confirm the runner is on 21
      - name: Verify Java version
        run:  java -version

      # 4 ▸ Build with Ant
      - name: Ant build
        run:  ant -noinput -buildfile build.xml

      # 5 ▸ Upload the jar(s) produced in build/jar
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Package
          path: build/jar
